[app]
name = nexus

[server]
#debug or release
RunMode = debug
HttpPort = 7070
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = postgres
User = things
Password = 123456
Host = 127.0.0.1
Port = 5432
Name = things
TablePrefix =
