[app]
name = nexus

[server]
#debug or release
RunMode = debug
HttpPort = 8080
ReadTimeout = 60
WriteTimeout = 60

[database]
Type = postgres
User = things
Password = 123456
Host = 127.0.0.1:3306
Name = things
TablePrefix = things_
